config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :courses do
    resources :sections do
      resources :lectures
    end
  end
  get "categories/get_subcategories"  
  resources :categories do
    resources :sub_categories
  end

  authenticated do
    root 'dashboard#index'
  end

  unauthenticated do
    root 'welcome#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses #, dependent: :destroy
  has_many :sub_categories, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :sub_category
  validates :title, presence: true,
                    length: { minimum: 6 }

  mount_uploader :image, ImageUploader

  has_many :sections, dependent: :destroy
  #has_many :lectures, through: :sections



end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :section
  #belongs_to :course
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course

  has_many :lectures, dependent: :destroy
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :courses #, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:full_name, :email, :password, :current_password, :title, :bio, :avatar, :fb_link, :tw_link, :li_link, :yt_link) }
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.create(category_params)
    @category.save
    redirect_to @category
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to  @category
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end
  
  def get_subcategories
    @data_category_id = params[:category_id]
    @data_subcategory_id = SubCategory.where(:category_id => @data_category_id).all
    render :json => @data_subcategory_id.map{|c| [c.id, c.name]}
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
    #@course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def edit
    #@course = Course.find(params[:id])
  end

  def create
    @user = current_user
    @course = @user.courses.create(course_params)

    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end

  def update
    #@course = Course.find(params[:id])
    if current_user == @course.user
      @course.update(course_params)
      redirect_to @course
    else
      render 'edit'
    end
  end

  def destroy
    #@course = Course.find(params[:id])
    if current_user == @course.user
      @course.destroy
    end

    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course)
      .permit(:title, :description, :image, :remote_image_url, :youtube_url, :price, :sale_price, :is_private)
  end

  def find_course
    @course = Course.find(params[:id])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController


  def new
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.new
  end

  def edit
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.find(params[:id])
  end

  def create
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.create(lecture_params)
    if @lecture.save
      redirect_to course_path(@course), notice: "Your lecture creation was successful."
    else
      render 'new'
    end
  end

  def update
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.find(params[:id])

    if @lecture.update(lecture_params)
      redirect_to @course
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.find(params[:id])
    #if current_user == @section.user
      @lecture.destroy
      redirect_to @course
    #end
  end

  private
  def lecture_params
    params.require(:lecture).permit(:title, :youtube_url)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def new
    @course = Course.find(params[:course_id])
    @section = @course.sections.new
  end

  def edit
    @course = Course.find(params[:course_id])
    @section = @course.sections.find(params[:id])
  end

  def create
    @course = Course.find(params[:course_id])
    @section = @course.sections.create(section_params)
    #@section.user = current_user
    @section.save
    redirect_to course_path(@course), notice: "Your section was successful."
  end

  def update
    @course = Course.find(params[:course_id])
    @section = @course.sections.find(params[:id])

    if @section.update(section_params)
      redirect_to @course
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:course_id])
    @section = @course.sections.find(params[:id])
    #if current_user == @section.user
      @section.destroy
      redirect_to @course
    #end
  end


  private
    def section_params
      params.require(:section).permit(:title)
    end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController

  def new
    @category = Category.find(params[:category_id])
    @sub_category = @category.sub_categories.new
  end

  def edit
    @category = Category.find(params[:category_id])
    @sub_category = @category.sub_categories.find(params[:id])
  end

  def create
    @category = Category.find(params[:category_id])
    @sub_category = @category.sub_categories.create(sub_category_params)
    @sub_category.save
    redirect_to @category
  end

  def update
    @category = Category.find(params[:category_id])
    @sub_category = @category.sub_categories.find(params[:id])
    @sub_category.update(sub_category_params)
    redirect_to @category
  end

  def destroy
    @category = Category.find(params[:category_id])
    @sub_category = @category.sub_categories.find(params[:id])
    @sub_category.destroy
    redirect_to @category
  end

  private
  def sub_category_params
    params.require(:sub_category).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/_list.html.erb
<% @categories.each do |category| %>
  <%= category.name %>
  <%= link_to 'View', category_path(category), class: "btn btn-link" %>
  <%= link_to 'Edit', edit_category_path(category), class: "btn btn-link" %>
    <%= link_to 'Delete', category_path(category),
          method: :delete,
          data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
  <br />
<% end %>

app/views/categories/edit.html.erb
edit

<%= render 'form' %>

app/views/categories/index.html.erb
<h1> List of Categories </h1>

<%= link_to "Create Category", new_category_path, class: "btn btn-secondary" %> <br />

<%= render 'list' %>

app/views/categories/new.html.erb
<h1> Create Categories <h1>

<%= render 'form' %>

app/views/categories/show.html.erb
show
<p>
  <strong>Category:</strong>
  <%= @category.name %>
</p> <br />
<%= link_to 'Create Sub-Category', new_category_sub_category_path(@category), class: "btn btn-default" %> <br />

<%= render 'sub_categories/list' %>

app/views/lectures/_form.html.erb
<%= form_for [@course, @section, @lecture] do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :youtube_url %><br>
    <%= f.text_field :youtube_url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/lectures/_lectures.html.erb
<% @section.lectures.each do |lecture| %>
    <em>Lecture: </em>
    <%= lecture.title %>

    <% if current_user == @course.user %>
      <%= link_to 'Edit', edit_course_section_lecture_path(@course, @section, lecture), class: "btn btn-link" %>
      <%= link_to 'Delete', [@course, @section, lecture],
                 method: :delete,
                 data: { confirm: 'Are you sure?', class: "btn btn-link" }
                  %>
    <br />
    <% end %>

    <br />
  <% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form' %>

app/views/lectures/new.html.erb
<h2>Add Lecture:</h2>
<%= render 'form' %>

app/views/sections/_form.html.erb
<%= form_for [@course, @section] do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/sections/_sections.html.erb
<% @course.sections.each do |section| %>

    <strong>Section: </strong>
    <%= section.title %>

    <% if current_user == @course.user %>

        <%= link_to 'Edit', edit_course_section_path(@course, section), class: "btn btn-link" %>
        <%= link_to 'Delete', [@course, section],
                   method: :delete,
                   data: { confirm: 'Are you sure?', class: "btn btn-link" }%> <br />
        <%= link_to 'Create Lecture', new_course_section_lecture_path(@course, section), class: "btn btn-default" %> <br />
        <br />


    <% end %>

  <%#= render 'lectures/lectures' %>
  <% section.lectures.each do |lecture| %>
    <em>Lecture: </em>
    <%= lecture.title %>

    <% if current_user == @course.user %>
      <%= link_to 'Edit', edit_course_section_lecture_path(@course, section, lecture), class: "btn btn-link" %>
      <%= link_to 'Delete', [@course, section, lecture],
                 method: :delete,
                 data: { confirm: 'Are you sure?', class: "btn btn-link" }
                  %>
    <br />
    <% end %>

    <br />
  <% end %>

<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

app/views/sections/new.html.erb
<h2>Add Sections:</h2>
<%= render 'form' %>

app/views/sub_categories/_form.html.erb
<%= form_for [@category, @sub_category] do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/sub_categories/_list.html.erb
<% @category.sub_categories.each do |sub_category| %>
    <%= sub_category.name %>
    <%= link_to 'Edit', edit_category_sub_category_path(@category, sub_category), class: "btn btn-link" %>
    <%= link_to 'Delete', category_sub_category_path(@category, sub_category),
          method: :delete,
          data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
  <br />
<% end %>

app/views/sub_categories/edit.html.erb
edit
<%= render 'form' %>

app/views/sub_categories/new.html.erb
new

<%= render 'form' %>