config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :courses do
    resources :sections do
      resources :lectures
    end
  end
  get "categories/get_subcategories"  
  resources :categories do
    resources :sub_categories
  end

  authenticated do
    root 'dashboard#index'
  end

  unauthenticated do
    root 'welcome#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses #, dependent: :destroy
  has_many :sub_categories, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :sub_category
  validates :title, presence: true,
                    length: { minimum: 6 }

  mount_uploader :image, ImageUploader

  has_many :sections, dependent: :destroy
  #has_many :lectures, through: :sections



end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :section
  #belongs_to :course
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course

  has_many :lectures, dependent: :destroy
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :courses #, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses, dependent: :destroy

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
    #@course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def edit
    #@course = Course.find(params[:id])
  end

  def create
    @user = current_user
    @course = @user.courses.create(course_params)

    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end

  def update
    #@course = Course.find(params[:id])
    if current_user == @course.user
      @course.update(course_params)
      redirect_to @course
    else
      render 'edit'
    end
  end

  def destroy
    #@course = Course.find(params[:id])
    if current_user == @course.user
      @course.destroy
    end

    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course)
      .permit(:title, :description, :image, :remote_image_url, :youtube_url, :price, :sale_price, :is_private)
  end

  def find_course
    @course = Course.find(params[:id])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController


  def new
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.new
  end

  def edit
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.find(params[:id])
  end

  def create
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.create(lecture_params)
    if @lecture.save
      redirect_to course_path(@course), notice: "Your lecture creation was successful."
    else
      render 'new'
    end
  end

  def update
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.find(params[:id])

    if @lecture.update(lecture_params)
      redirect_to @course
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:course_id])
    @section = Section.find(params[:section_id])
    @lecture = @section.lectures.find(params[:id])
    #if current_user == @section.user
      @lecture.destroy
      redirect_to @course
    #end
  end

  private
  def lecture_params
    params.require(:lecture).permit(:title, :youtube_url)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def new
    @course = Course.find(params[:course_id])
    @section = @course.sections.new
  end

  def edit
    @course = Course.find(params[:course_id])
    @section = @course.sections.find(params[:id])
  end

  def create
    @course = Course.find(params[:course_id])
    @section = @course.sections.create(section_params)
    #@section.user = current_user
    @section.save
    redirect_to course_path(@course), notice: "Your section was successful."
  end

  def update
    @course = Course.find(params[:course_id])
    @section = @course.sections.find(params[:id])

    if @section.update(section_params)
      redirect_to @course
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:course_id])
    @section = @course.sections.find(params[:id])
    #if current_user == @section.user
      @section.destroy
      redirect_to @course
    #end
  end


  private
    def section_params
      params.require(:section).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
footer here

app/views/layouts/_header.html.erb
header here

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
      <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <%= link_to "UDEMYClone", root_path, class: "btn navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li> <%= link_to "Browse Courses", courses_path, class: "btn btn-link" %></li>
            <% if user_signed_in? %>
              <li> <%= link_to "Create Course", new_course_path, class: "btn btn-secondary" %>
              </li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li> <%= current_user.username %> </li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-link" %> </li>

                  <li role="separator" class="divider"></li>
                    <%= link_to "Categories", categories_path, class: "btn btn-link" %>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-link" %></li>
                </ul>
              </li>
            <% else %>

              <li><%= link_to "Login", new_user_session_path, class: "btn btn-link" %></li>
              <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default" %></li>
            <% end %>

          </ul>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UdemyClone</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" >
      <div class="row" >
        <% if flash.count > 0 %>
          <div class="well well-sm">
            <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, id: "flash_#{name}" %>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_home.html.erb
<%= image_tag 'webbanner1.jpg' %>